### PR TITLE
Simple STUN client implementation

### PR DESCRIPTION
**Pull request by iwittkau**
as discussed in #15

### CODE REVIEW

**Comment by Sean-Der** [comment]
This is fantastic! This is even better then I thought, since you made it extendable people can write their own clients in the future.

If we add TURN people could build a client to share data between two servers (if you only have one public IP you can use this to get through and send data to your internal network) and cool little hacks like that. Not limited at all to just communication software. 

Would you mind fixing the errors in https://travis-ci.org/pions/turn/jobs/382261783 and then will merge it right away!

**Comment by iwittkau** [comment]
> Would you mind fixing the errors in https://travis-ci.org/pions/turn/jobs/382261783 and then will merge it right away!

**Comment by Sean-Der** [comment]
Yea! They are all defined in the [.travis.yml](https://github.com/pions/turn/blob/master/.travis.yml)
You should be able to `go get` and install the checks, and then run them in the root of the project. 

Also if you want you should add a CONTRIBUTORS section to the README and put your name in there! If you do would you also mind adding winds2016 they tested on Windows and reported a bunch of bugs.

thanks again for your work on this!

**Comment by Sean-Der** [comment]
Hey @iwittkau 

Anything I can do to help with this? I am happy to merge and then fix (if you don't mind me changing your work) some people prefer to finish the whole task.

either works for me! thanks

**Comment by iwittkau** [comment]
@Sean-Der sorry, I had a very busy schedule during the last seven days. Let me see what I can fix. I'll let you know if I encounter any problems.

**Comment by iwittkau** [comment]
Well, that wasn't too hard 👍

**Comment by Sean-Der** [comment]
Nice work! Sorry didn't mean to rush you, I just wanted to make sure your stuff got in (never had to really maintain/take contributions before)

Since you were in the code does everything look go overall? Anything you would change?

**Comment by iwittkau** [comment]
> Nice work! Sorry didn't mean to rush you, I just wanted to make sure your stuff got in (never had to really maintain/take contributions before)

No problem, I'm also ab beginner at this. I never really contributed to project before.

> Since you were in the code does everything look go overall? Anything you would change?

I stumbled at the `internal` package, never worked with an internal package. But since this a standard go way of doing things, it seems I have to get used to this. Some tools allow you to still use an internal package some are more strict, that was where I was a little confused.

> Thanks again for build that, I think people will really like that.

I'm here to contibute more in the future and ready to bugfix if needed.

**Pull request merged**
